modLoader="javafml"
loaderVersion="[47,)"
license="Apache-2.0"
issueTrackerURL=""

[[mods]]
modId="logtosplunk"
version="${file.jarVersion}"
displayName="Splunk for Minecraft (Forge)"
authors="Splunk"
description='''
Logs Minecraft server events (player, block, death) to Splunk via the HTTP Event Collector.
'''

[[dependencies.logtosplunk]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.logtosplunk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="SERVER"
